// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzWdKyV-d1f3DU7t7jWa5b096KUy3aw6U',
    appId: '1:1071776021725:web:2dc90409d7cf4fc7a5ef34',
    messagingSenderId: '1071776021725',
    projectId: 'ecommerce-40890',
    authDomain: 'ecommerce-40890.firebaseapp.com',
    storageBucket: 'ecommerce-40890.firebasestorage.app',
    measurementId: 'G-4QQFLM0MRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApqHN70EsGOxafYAOaEo8KnWsbGh94Ze0',
    appId: '1:1071776021725:android:52ba876640fb3a9aa5ef34',
    messagingSenderId: '1071776021725',
    projectId: 'ecommerce-40890',
    storageBucket: 'ecommerce-40890.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfqTXOGlcpZbYUKXIvxZBSx8fMkhiQNmg',
    appId: '1:1071776021725:ios:839c1de7acab453fa5ef34',
    messagingSenderId: '1071776021725',
    projectId: 'ecommerce-40890',
    storageBucket: 'ecommerce-40890.firebasestorage.app',
    iosBundleId: 'com.example.meuAppFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfqTXOGlcpZbYUKXIvxZBSx8fMkhiQNmg',
    appId: '1:1071776021725:ios:839c1de7acab453fa5ef34',
    messagingSenderId: '1071776021725',
    projectId: 'ecommerce-40890',
    storageBucket: 'ecommerce-40890.firebasestorage.app',
    iosBundleId: 'com.example.meuAppFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzWdKyV-d1f3DU7t7jWa5b096KUy3aw6U',
    appId: '1:1071776021725:web:9e43a0722376a57fa5ef34',
    messagingSenderId: '1071776021725',
    projectId: 'ecommerce-40890',
    authDomain: 'ecommerce-40890.firebaseapp.com',
    storageBucket: 'ecommerce-40890.firebasestorage.app',
    measurementId: 'G-VJ0LJCZ7SP',
  );
}
